syntax = "proto3";

package Inventory;

service InventoryService {
    rpc CheckRecipeAvailability (CheckRecipeAvailabilityRequest) returns (CheckRecipeAvailabilityResponse);
    rpc ConsumeRecipeIngredients (ConsumeRecipeIngredientsRequest) returns (ConsumeRecipeIngredientsResponse);
}

message CheckRecipeAvailabilityRequest {
}

message CheckRecipeAvailabilityResponse {
    bool available = 1;
}

message ConsumeRecipeIngredientsRequest {
    repeated ConsumeRecipeIngredientsTask ConsumeRecipeIngredientsTasks = 1;
}

message ConsumeRecipeIngredientsTask {
    string recipe_name = 1;
    int32 quantity = 2;
}

message ConsumeRecipeIngredientsResponse {
    repeated ConsumeRecipeIngredientsResult ConsumeRecipeIngredientsResults = 1;
}

message ConsumeRecipeIngredientsResult {
    string recipe_name = 1;
    bool consumed = 2;
    string comments = 3;
}